name: "Aileen and Manik"
description: "We're getting married!"
url: http://blog.manikrathee.com

#gems:        []
#timezone:    nil
#encoding:    nil

permalink: /posts/:year/:month/:day/:title.html

safe: false
markdown:      kramdown
highlighter: true

sitemap:
    file: "/sitemap.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# include: [".htaccess"]
exclude: ['gruntfile.js', 'package.json', '/node_modules', '*.psd']
keep_files:  ['.git']

host:        0.0.0.0
port:        4000
